### ISSUE TITLE
Unable to execute pipeline

### ISSUE THREAD

**Issue by ChallaSailendra** [microsoftgraph/group-membership-management#31]
We are trying to build GMM as per your blog ,while at the execution of pipeline we are getting some errors.Please find below the error messages:-

##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
##[error]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\2.0.2210.2\Service\GroupMembershipManagement\Hosts\JobTrigger\Services.Tests
##[warning]RetryHelper encountered task failure, will retry (attempt #: 2 out of 3) after 4000 ms
[Pipleline log.pdf](https://github.com/microsoftgraph/group-membership-management/files/9820034/Pipleline.log.pdf)

[Pipleline log.pdf](https://github.com/microsoftgraph/group-membership-management/files/9820022/Pipleline.log.pdf)

**Comment by danielluo-msft** [comment]
Hi @ChallaSailendra ,

We are working on pushing out a new update to our public repo soon that would resolve this issue.
But in the meantime, to fix this issue:
"The total line coverage is below the specific 93"
Update that value for JobTrigger coverageThreshold within your vsts-cicd.yml file from 93 to 89:
    - function:
       name: 'JobTrigger'
       coverageThreshold: 89

**Comment by ChallaSailendra** [comment]
Hi Daniello,
 
Still we are facing the same issue ,attaching the logs for your reference
[logs_46.zip](https://github.com/microsoftgraph/group-membership-management/files/10153975/logs_46.zip)
[logs_46.zip](https://github.com/microsoftgraph/group-membership-management/files/10153979/logs_46.zip)

**Comment by ChallaSailendra** [comment]
[](url)Hi @danielluo-msft, 

We run the pipeline, below is the screenshot of the pipeline results. Can you help why last 2 activities in pipeline skipped. 

[](![image](https://user-images.githubusercontent.com/95159997/205642381-a1ba8389-ec8a-4eff-beca-6ba0e886bcd7.png))


And also help me output of the pipeline if pipeline succeeded.

**Comment by ChallaSailendra** [comment]
Hi @danielluo-msft,

We run the pipeline, below is the screenshot of the pipeline results. Can you help why last 2 activities in pipeline skipped.
pipeline and And also help me output of the pipeline if pipeline succeeded.

Attaching the logs for your reference.
[logs_46.zip](https://github.com/microsoftgraph/group-membership-management/files/10163023/logs_46.zip)

![pipeline](https://user-images.githubusercontent.com/95159997/205827184-8901a1f5-8d99-4f07-93dc-9c7fddc27713.PNG)

**Comment by ChallaSailendra** [comment]
Hi @danielluo-msft,

We run the pipeline, below is the screenshot of the pipeline results. Can you help why last 2 activities in pipeline skipped.
pipeline and And also help me output of the pipeline if pipeline succeeded.

Attaching the logs for your reference.
![pipeline](https://user-images.githubusercontent.com/95159997/205827838-7012cb3e-04d0-4d64-b292-966599fde432.PNG)
[logs_46.zip](https://github.com/microsoftgraph/group-membership-management/files/10163032/logs_46.zip)

**Comment by ChallaSailendra** [comment]
Looking for some help for the above errors.

**Comment by alrios-ms** [comment]
Hi @ChallaSailendra,

Looking at the logs the issue seems to be similar as the one described by @danielluo-msft for the code coverage.

You might need to update the value of coverageThreshold within your vsts-cicd.yml file for your functions.
Based on the numbers from your logs, I will suggest these:

GraphUpdater - 70
SecurityGroup - 80
JobScheduler - 40

Regarding AzureTableBackup the error message is "Project file(s) matching the specified pattern were not found." It seems there might be files missing for this function in your directory. 

FYI: AzureTableBackup function has been renamed to [AzureMaintenance](https://github.com/microsoftgraph/group-membership-management/tree/main/Service/GroupMembershipManagement/Hosts/AzureMaintenance) in the latest version.

**Comment by ChallaSailendra** [comment]
Hi Alrios,

Thank you for your response, As you suggested made the changes and execute the pipeline. Successfully moved forwarded now we are seeing different error .

Sharing the logs.

[logs_54.zip](https://github.com/microsoftgraph/group-membership-management/files/10224656/logs_54.zip)
![gmm_Error](https://user-images.githubusercontent.com/95159997/207515078-08ad9f1b-7436-4372-8ec7-e8c64e1836b1.PNG)

**Comment by ChallaSailendra** [comment]
Hi Alrios,

We renamed AzureTableBackup with AzureMaintenance and update the value as suggested and rerun the pipeline .
Expect NonProd_int all other jobs are executed successfully .Could you please help me sharing the logs for your reference
![GMM_Nonprod](https://user-images.githubusercontent.com/95159997/207522070-95df9f1e-44e9-49f1-874d-65d6e238295c.PNG)

[logs_55.zip](https://github.com/microsoftgraph/group-membership-management/files/10224878/logs_55.zip)

**Comment by ChallaSailendra** [comment]
Hi Team,

Looking for your support hand on the issue

**Comment by alrios-ms** [comment]
Hi @ChallaSailendra ,

I see you renamed the AzureTableBackup function, my intention was just to let you know the function has been renamed in the latest version, manually renaming it is not necessary. I am sorry for the confusion.

Based on the screenshot and the logs provided, I noticed a couple of things:

You are using the "int" environment for this deployment based off of your main branch, note that the deployment condition for "int" expects the branch to be "develop".
You would need to update the condition to replace "develop" or add "main", similar to UA.

INT 
[eq(variables['Build.SourceBranch'], 'refs/heads/develop')](https://github.com/microsoftgraph/group-membership-management/blob/d009104558b228b6e74e4a601145dde03affbe42/vsts-cicd.yml#L96L101)

UA
[in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main')](https://github.com/microsoftgraph/group-membership-management/blob/d009104558b228b6e74e4a601145dde03affbe42/vsts-cicd.yml#L137L142)


The other thing, you are using the default names "gmm" and "int", which might cause name collisions.

_"[We recommend trying to use unique <SolutionAbbreviation> and <EnvironmentAbbreviation> names, since some resources in Azure require to have unique names globally so it is possible to have name collisions.](https://github.com/microsoftgraph/group-membership-management/blob/main/README.md#note)"_

**Comment by ChallaSailendra** [comment]
Hi Alrios ,

Thank you for your help..we made the changes and executed them again, but still we see some error messages hope you can help us to resolve it . Attach the logs and screenshots.

[logs_58.zip](https://github.com/microsoftgraph/group-membership-management/files/10267487/logs_58.zip)
![Capture](https://user-images.githubusercontent.com/95159997/208643674-e7a2c163-61aa-4e11-9ceb-b65fed188b44.PNG)

**Comment by ChallaSailendra** [comment]
HI Team,

Any suggestions for the above errors

**Comment by danielluo-msft** [comment]
Hi @ChallaSailendra,

It looks like there is an issue with the deployment on the Azure side so there isn't enough details in the DevOps side to be able to determine the cause. Can you go to your resource group for GMM (start with the data resource group) and take a look at the "Deployments" blade on the left side for that resource group? That should provide more details on the issue so you can know what failed in the deployment.

![image](https://user-images.githubusercontent.com/89803072/209181038-b53872ad-a508-411a-89c9-f0068b0572c0.png)

**Comment by ChallaSailendra** [comment]
![gmmsnip](https://user-images.githubusercontent.com/95159997/209318502-7fff6627-5945-41de-8f12-3a5369f4d168.PNG)
Hi Danielluo,

Thanks for you reponse,Verified in deployment tab
"{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VaultNotFound","message":"The specified vault 'gmm-data-int' could not be found. This error can happen if the vault was placed in a recoverable state by deleting the vault. Ensure that either the vault was successfully created or that it is not in a recoverable state. To view the vaults in recoverable state you can follow this link https://go.microsoft.com/fwlink/?linkid=2149745 and recover the vault."}]}"

**Comment by ChallaSailendra** [comment]
Hi Team,

Waiting for your support.

**Comment by alrios-ms** [comment]
Hi @ChallaSailendra,

Most likely the keyvault was not created, as I mentioned earlier, the default environment names 'int', 'ua', 'prodv2' must not be reused since some resources like KeyVaults have global unique names, if another person is already using gmm-data-int, no one else would be able to reuse that name.

See [GMM Environments](https://github.com/microsoftgraph/group-membership-management#gmm-environments) for more information.

**Comment by ChallaSailendra** [comment]
HI Team,

Thank you for all your support, we are able to deploy all the configurations in the environment.
When we onboarded a schedule job ,getting below error message in the logs.
Caught unexpected exception in Part# 2, marking sync job as errored. Exception:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 739
at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.ScheduleDurableHttpActivityAsync(DurableHttpRequest req) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 308
at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationContext.CallHttpAsync(DurableHttpRequest req) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 271
at Hosts.SecurityGroup.OrchestratorFunction.RunOrchestratorAsync(IDurableOrchestrationContext context) in D:\a\1\2.0.2301.2\Service\GroupMembershipManagement\Hosts\SecurityGroup\Function\Orchestrator\OrchestratorFunction.cs:line 122
location_s
SecurityGroup
DryRun_s
False
slot_s
Production
event_s
RunOrchestratorAsync
operation_s
OrchestratorFunction
Type
ApplicationLog_CL

**Comment by alrios-ms** [comment]
Hi @ChallaSailendra 

Based on your logs, SecurityGroup function is failing when calling MembershipAggregator function, it is getting a 401 (Unauthorized) code, for context when SecurityGroup calls the MembershipAggregator function, a function key must be passed as part of the url in order to authorize that call. Please verify that the function key that SecurityGroup is using is correct following this steps.

1. Go to your MembershipAggregator function
2. This is the MembershipAggregator function key, we need to verify that the default function key is the one being used by the SecurityGroup function.
![image](https://user-images.githubusercontent.com/70599097/214723544-34a14925-c23a-42d6-b851-ded5445ab417.png)
3. Go to your SecurityGroup function
4. In the Configuration section, edit this setting "membershipAggregatorFunctionKey" it will have a value similar to this one
@Microsoft.KeyVault(SecretUri=https://gmm-data-test.vault.azure.net/secrets/membershipAggregatorFunctionKey/a321a335210b4c98976b05bf7d2775c0)
The last section of the value indicates the version of the secret that is being used, in this case it is: "a321a335210b4c98976b05bf7d2775c0"

![image](https://user-images.githubusercontent.com/70599097/214724406-a1762db4-4538-4724-8761-c98ce2ff254f.png)

5. Now we need to verify the actual value of that secret in your data keyvault.
Open your `<gmm>-data-<env>` keyvault and navigate to Secrets
![image](https://user-images.githubusercontent.com/70599097/214725444-d8358cdb-b15b-4a01-aa11-2cb9eaa7d24e.png)
Open your "membershipAggregatorFunctionKey" secret, you might see different versions, something like this.
![image](https://user-images.githubusercontent.com/70599097/214726570-050ef873-36ca-4547-bd0f-99b2ed80ab26.png)
Locate the version that SecurityGroup is using (from Step 4) and show the secret value.
The value displayed here must match that one from Step 2 in order to work.
![image](https://user-images.githubusercontent.com/70599097/214726900-42de4898-e270-4464-8d59-67abd6b91d60.png)

If they don't match, try redeploying your code that should update the function keys accordingly.

**Comment by ChallaSailendra** [comment]
Hi Team,

Thank you for the help, We verified and made changes as proposed. Now when we are executing the script "New-GmmSecurityGroupSyncJob" getting below errors .
Please find the attachment of error message.
![Uploading Capture_Error.PNG…]()

Get-AzADGroup : Cannot process argument transformation on parameter 'ObjectId'. Cannot convert value "[{"type":"SecurityGroup"" to type 
"System.Guid". Error: "Expected {0xdddddddd, etc}."
At line:120 char:79
+ ... uery.Split(",") | ForEach-Object { Get-AzADGroup -ObjectId $_ } | For ...
+                                                                ~~
    + CategoryInfo          : InvalidData: (:) [Get-AzADGroup], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-AzADGroup
