### ISSUE TITLE
Error after long time of sync

### ISSUE THREAD

**Issue by dborchers-gc** [microsoftgraph/group-membership-management#33]
After some weeks of no change from agroup, the Job seems to be switch to "Error"

![2022-11-24 09_14_46-Window](https://user-images.githubusercontent.com/63800439/203729431-57199108-a844-45f0-899b-a0d1ba911460.png)

The detailed Message is this:
"Unexpected exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 742
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.ScheduleDurableHttpActivityAsync(DurableHttpRequest req) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 308
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationContext.CallHttpAsync(DurableHttpRequest req) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 271
   at Hosts.MembershipAggregator.OrchestratorFunction.RunOrchestratorAsync(IDurableOrchestrationContext context) in D:\a\1\2.0.2208.5\Service\GroupMembershipManagement\Hosts\MembershipAggregator\Function\Orchestrator\OrchestratorFunction.cs:line 101"

Do you have an Idea what this could be?

**Comment by alrios-ms** [comment]
@dborchers-gc Looks like the HTTP call from MembershipAggregator to GraphUpdater failed for some reason, unfortunately the exception message doesn't provide enough information, would you mind checking your Application Insights logs around the time this error occurred, hopefully there will be more information there.

**Comment by dborchers-gc** [comment]
Sure I can. Could you tell me what I have to look for? Or what’s the right filters?

And do you have an idea how I can set it back to work?

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: alrios-ms ***@***.***>
Gesendet: Tuesday, November 29, 2022 6:46:59 PM
An: microsoftgraph/group-membership-management ***@***.***>
Cc: Daniel Remmers ***@***.***>; Mention ***@***.***>
Betreff: Re: [microsoftgraph/group-membership-management] Error after long time of sync (Issue #33)


@dborchers-gc<https://github.com/dborchers-gc> Looks like the HTTP call from MembershipAggregator to GraphUpdater failed for some reason, unfortunately the exception message doesn't provide enough information, would you mind checking your Application Insights logs around the time this error occurred, hopefully there will be more information there.

**Comment by alrios-ms** [comment]
You could try this query:

`exceptions
| where timestamp >= todatetime('2022-11-29T17:22:21.1516534Z') and timestamp <= todatetime('2022-11-29T17:22:21.1516534Z') 
| where problemId contains "exception"
| order by timestamp`

Update both dates to a time range when the exception occurred



To update the job so it gets processed again:

1. In the Azure Portal locate and open your jobs storage account, naming convention `jobs<environment><random-string>` 
2. Click on Tables
![image](https://user-images.githubusercontent.com/70599097/204628908-af4c7841-c8ff-4211-a480-ef0f089f836e.png)
3. Click on the syncJobs table
4. Locate the record you want to edit 
5. Right click -> Edit -> Set the Status to Idle - case sensitive -
![image](https://user-images.githubusercontent.com/70599097/204630575-9120f63b-6df5-4a22-9031-c96ae8e3ed59.png)
6. Click on Update button

Let me know if you have further questions.

**Comment by dborchers-gc** [comment]
Maybe this helps? Its from the Exceptions Logs

![image](https://user-images.githubusercontent.com/63800439/204855659-e31fd555-7186-4c6a-ab5a-c986a57398bf.png)

![image](https://user-images.githubusercontent.com/63800439/204855880-522fbb90-4176-418e-be83-81ddc9f32358.png)

These are the main entries in that time range
